version: '3.8'

services:
  # The MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: nymo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  bot:
    build: .
    container_name: nymo-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nymo_db
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}

volumes:
  mongo-data:
