version: '3.8'

services:
  # The MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: nymo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  bot:
    build: .
    container_name: nymo-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nymo_db
      - DISCORD_TOKEN=${DISCORD_TOKEN}

volumes:
  mongodb_data:
